name: PlayerCountryInfo
version: '${project.version}'
main: de.stylelabor.dev.playercountryinfo.PlayerCountryInfo
api-version: '1.20'
commands:
  pci-reload:
    description: Reloads the PlayerCountryInfo plugin
    usage: /<command>